# Use postgres/example user/password credentials
version: '3.6'

services:

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: my_pass
    ports:
      - 5433:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  postgres_adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  
